apiVersion: v1
kind: Service
metadata:
  name: hbservice-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    app: hbservice
    type: api


#kubectl create -f service.yml
##kubectl get services